const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('feg', {
  pickFiles: opts => ipcRenderer.invoke('pick-files', opts),
  pickSave: name => ipcRenderer.invoke('pick-save', name),
  runQC: file => ipcRenderer.invoke('run-qc', file),
  buildMaster: opts => ipcRenderer.invoke('build-master', opts),
  onBuildProgress: cb => ipcRenderer.on('build-progress', (_e, stage) => cb(stage)),
  checklistDefs: () => ipcRenderer.invoke('checklist-defs'),
  loadProjects: () => ipcRenderer.invoke('load-projects'),
  saveProjects: p => ipcRenderer.invoke('save-projects', p),
  renameFiles: jobs => ipcRenderer.invoke('rename-files', jobs),
  loadSettings: () => ipcRenderer.invoke('load-settings'),
  saveSettings: s => ipcRenderer.invoke('save-settings', s),
  notionTest: args => ipcRenderer.invoke('notion-test', args),
  notionEpisodes: () => ipcRenderer.invoke('notion-episodes'),
  notionPushQC: args => ipcRenderer.invoke('notion-push-qc', args),
  notionSetAsset: args => ipcRenderer.invoke('notion-set-asset', args),
  notionSetStatus: args => ipcRenderer.invoke('notion-set-status', args),
  notionCreateEpisode: f => ipcRenderer.invoke('notion-create-episode', f),
  notionCreateChecklist: args => ipcRenderer.invoke('notion-create-checklist', args),
  notionSetChecklistItem: args => ipcRenderer.invoke('notion-set-checklist-item', args),
  stageDefs: () => ipcRenderer.invoke('stage-defs'),
  guideDefs: () => ipcRenderer.invoke('guide-defs'),
  pickDirectory: () => ipcRenderer.invoke('pick-directory'),
  openExternal: url => ipcRenderer.invoke('open-external', url),
  openFolder: p => ipcRenderer.invoke('open-folder', p),
  intakeCheck: args => ipcRenderer.invoke('intake-check', args),
  intakeFile: args => ipcRenderer.invoke('intake-file', args),
  notionSetDropboxPath: args => ipcRenderer.invoke('notion-set-dropbox-path', args),
  ensureDistFolders: args => ipcRenderer.invoke('ensure-dist-folders', args),
  templateDefs: () => ipcRenderer.invoke('template-defs'),
  exportDoc: args => ipcRenderer.invoke('export-doc', args),
  parseSequenceXml: p => ipcRenderer.invoke('parse-sequence-xml', p),
  scanAeps: root => ipcRenderer.invoke('scan-aeps', root),
  farmSendBatch: (aeps, mode, format) => ipcRenderer.invoke('farm-send-batch', { aeps, mode, format }),
  farmCancelBatch: () => ipcRenderer.invoke('farm-cancel-batch'),
  onFarmProgress: cb => ipcRenderer.on('farm-progress', (_e, msg) => cb(msg)),
  makeTextlessXml: args => ipcRenderer.invoke('make-textless-xml', args),
  makeCleanXml: args => ipcRenderer.invoke('make-clean-xml', args),
  verifyTextless: args => ipcRenderer.invoke('verify-textless', args),
  onOcrProgress: cb => ipcRenderer.on('ocr-progress', (_e, msg) => cb(msg)),
  stemsBuild: args => ipcRenderer.invoke('stems-build', args),
  stemsEmbed: args => ipcRenderer.invoke('stems-embed', args),
  stemsPad: args => ipcRenderer.invoke('stems-pad', args),
  onStemProgress: cb => ipcRenderer.on('stem-progress', (_e, msg) => cb(msg)),
  parseCaptions: p => ipcRenderer.invoke('parse-captions', p),
  retimeCaptions: p => ipcRenderer.invoke('retime-captions', p),
  writeTextFile: args => ipcRenderer.invoke('write-text-file', args),
});
